// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6muU1XDxjQL6ftxoQcoYUFjFLktfI7s',
    appId: '1:111394228371:web:fa795b23562c75cc1f2566',
    messagingSenderId: '111394228371',
    projectId: 'expert-app-backend',
    authDomain: 'expert-app-backend.firebaseapp.com',
    databaseURL: 'https://expert-app-backend-default-rtdb.firebaseio.com',
    storageBucket: 'expert-app-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslMpXJHBm7CMXPSHgI-jNLAHz-18M4XY',
    appId: '1:111394228371:android:ec8cb927980b8f0d1f2566',
    messagingSenderId: '111394228371',
    projectId: 'expert-app-backend',
    databaseURL: 'https://expert-app-backend-default-rtdb.firebaseio.com',
    storageBucket: 'expert-app-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aERyvJHPgQT9BNWDP4JpmPZmplekWTA',
    appId: '1:111394228371:ios:2658d258476441ea1f2566',
    messagingSenderId: '111394228371',
    projectId: 'expert-app-backend',
    databaseURL: 'https://expert-app-backend-default-rtdb.firebaseio.com',
    storageBucket: 'expert-app-backend.appspot.com',
    androidClientId: '111394228371-edlq6mu7f1je3thj3jpt9o96a3ih6m5u.apps.googleusercontent.com',
    iosClientId: '111394228371-0dcs9gu3ckvfjvqahinaitvi6gqp4vdi.apps.googleusercontent.com',
    iosBundleId: 'com.backend.expertapp',
  );
}
