// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK6muU1XDxjQL6ftxoQcoYUFjFLktfI7s',
    appId: '1:111394228371:web:fa795b23562c75cc1f2566',
    messagingSenderId: '111394228371',
    projectId: 'expert-app-backend',
    authDomain: 'expert-app-backend.firebaseapp.com',
    databaseURL: 'https://expert-app-backend-default-rtdb.firebaseio.com',
    storageBucket: 'expert-app-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslMpXJHBm7CMXPSHgI-jNLAHz-18M4XY',
    appId: '1:111394228371:android:ec8cb927980b8f0d1f2566',
    messagingSenderId: '111394228371',
    projectId: 'expert-app-backend',
    databaseURL: 'https://expert-app-backend-default-rtdb.firebaseio.com',
    storageBucket: 'expert-app-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlqT1a4dtqp41Phy174YuidoDBC1olhnM',
    appId: '1:111394228371:ios:53103fc884382a4d1f2566',
    messagingSenderId: '111394228371',
    projectId: 'expert-app-backend',
    databaseURL: 'https://expert-app-backend-default-rtdb.firebaseio.com',
    storageBucket: 'expert-app-backend.appspot.com',
    iosClientId: '111394228371-t0lrrbq4vqsp87g8b3c0q5d0lvspv6vo.apps.googleusercontent.com',
    iosBundleId: 'com.example.expertapp',
  );
}
